# Constants for the game world
GAME_WINDOW_WIDTH = 1000
GAME_WINDOW_HEIGHT = 1000
GAME_WINDOW_CHANNELS = 3
BACKGROUND_COLOUR = [255, 177, 105]
OBSERVATION_SCALE = 0.1
OBSERVATION_WIDTH = int(GAME_WINDOW_WIDTH * 0.1)
OBSERVATION_HEIGHT = int(GAME_WINDOW_HEIGHT * 0.1)
TIME_REWARD_THRESHOLD = 50
MISSILE_THRESHOLD = 25
TIME_REWARD = 1
LOSS_REWARD = -100
ENEMY_CRASH_REWARD = 50
MISSILE_REWARD = 100
ENEMY_MISSILE_CHANCE = 100
SPAWN_ENEMIES_INTERVAL = 4

# Constants for different game objects
SHIP_MAX_SPEED = 5
SHIP_MIN_SPEED = -2
MISSILE_SPEED = 10
ROTATION_ANGLE = 3
TURN_LEFT = 0
TURN_RIGHT = 1
ACCELERATE = 2
DECELERATE = 3
FIRE_MISSILE = 4
DO_NOTHING = 5

