# Constants for the game world
GAME_WINDOW_WIDTH = 1000
GAME_WINDOW_HEIGHT = 1000
GAME_WINDOW_CHANNELS = 3
BACKGROUND_COLOUR = [255, 177, 105]
OBSERVATION_SCALE = 0.1
OBSERVATION_WIDTH = int(GAME_WINDOW_WIDTH * 0.1)
OBSERVATION_HEIGHT = int(GAME_WINDOW_HEIGHT * 0.1)

# Constants for different game objects
SHIP_MAX_SPEED = 5
SHIP_MIN_SPEED = -2
MISSILE_SPEED = 15

